export default {
	'/introduction/mainnet-beta': '/how-skale-works/mainnet-beta',
	'/introduction': '/welcome/intro-to-skale',
	'/introduction/overview': '/welcome/get-started',
	'/introduction/skale-and-ethereum-security': '/how-skale-works/consensus',
	'/introduction/skale-chain-fuel': '/building-applications/gas-fees',
	'/introduction/skale-chain-types': '/building-applications/pick-a-chain',
	'/introduction/skale-hybrid-layer': '/how-skale-works/consensus',
	'/introduction/zero-gas-fees': '/building-applications/gas-fees',
	'/introduction/faq': '/welcome/intro-to-skale',

	// Develop Section → Building Applications
	'/develop': '/building-applications/build-a-dapp',
	'/develop/deployment': '/building-applications/deploy-on-skale',
	'/develop/faq': '/building-applications/troubleshooting',
	'/develop/high-performance-dapps': '/building-applications/build-a-dapp',
	'/develop/sfuel': '/faucet',
	'/develop/sfuel/distribution/api-distribution': '/building-applications/gas-fees',
	'/develop/sfuel/distribution/proof-of-work-distribution': '/building-applications/gas-fees',
	'/develop/sfuel/etherbase': '/building-applications/gas-fees',
	'/develop/sfuel/gas-vs-sfuel': '/building-applications/gas-fees',
	'/develop/sfuel/pow-vs-sfuel': '/building-applications/gas-fees',
	'/develop/sfuel/proof-of-work': '/building-applications/gas-fees',
	'/develop/sfuel/sfuel-distribution': '/building-applications/gas-fees',
	'/develop/sfuel/sfuel-station': '/faucet',

	// Delegators/Validators Section → Run a SKALE Node
	'/delegators': '/run-a-skale-node/overview',
	'/delegators/delegation-faq': '/run-a-skale-node/faq',
	'/validators': '/run-a-skale-node/overview',
	'/validators/validator-faq': '/run-a-skale-node/faq',

	// Governance Section → How SKALE Works
	'/governance': '/how-skale-works/skl-token',
	'/governance/how-to-vote': '/how-skale-works/skl-token',
	'/governance/intro-skale-dao': '/how-skale-works/skl-token',
	'/governance/skale-dao': '/how-skale-works/skl-token',
	'/governance/skl-token': '/how-skale-works/skl-token',

	// IMA Section → SKALE Bridge (All Versions)
	'/ima/1.0.x': '/skale-bridge/overview',
	'/ima/1.0.x/access-control': '/skale-bridge/messaging-layer/connect-custom-contracts',
	'/ima/1.0.x/api/mainnet/communitypool': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.0.x/api/mainnet/depositbox': '/skale-bridge/ethereum/bridge-erc20',
	'/ima/1.0.x/api/mainnet/depositboxes/depositboxerc1155': '/skale-bridge/ethereum/bridge-erc1155',
	'/ima/1.0.x/api/mainnet/depositboxes/depositboxerc20': '/skale-bridge/ethereum/bridge-erc20',
	'/ima/1.0.x/api/mainnet/depositboxes/depositboxerc721': '/skale-bridge/ethereum/bridge-erc721',
	'/ima/1.0.x/api/mainnet/depositboxes/depositboxeth': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.0.x/api/mainnet/linker': '/skale-bridge/overview',
	'/ima/1.0.x/api/mainnet/skalemanagerclient': '/skale-bridge/overview',
	'/ima/1.0.x/api/mainnet/twin': '/skale-bridge/overview',
	'/ima/1.0.x/api/messageproxy': '/skale-bridge/messaging-layer/message-proxy',
	'/ima/1.0.x/api/schain/communitylocker': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.0.x/api/schain/keystorage': '/skale-bridge/overview',
	'/ima/1.0.x/api/schain/messageproxyforschain': '/skale-bridge/messaging-layer/message-proxy',
	'/ima/1.0.x/api/schain/tokenmanager': '/skale-bridge/overview',
	'/ima/1.0.x/api/schain/tokenmanagerlinker': '/skale-bridge/overview',
	'/ima/1.0.x/api/schain/tokenmanagers/tokenmanagererc1155': '/skale-bridge/ethereum/bridge-erc1155',
	'/ima/1.0.x/api/schain/tokenmanagers/tokenmanagererc20': '/skale-bridge/ethereum/bridge-erc20',
	'/ima/1.0.x/api/schain/tokenmanagers/tokenmanagererc721': '/skale-bridge/ethereum/bridge-erc721',
	'/ima/1.0.x/api/schain/tokenmanagers/tokenmanagereth': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.0.x/flows': '/skale-bridge/overview',
	'/ima/1.0.x/funding-exits': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.0.x/getting-started': '/skale-bridge/overview',
	'/ima/1.0.x/managing-erc1155': '/skale-bridge/ethereum/bridge-erc1155',
	'/ima/1.0.x/managing-erc20': '/skale-bridge/ethereum/bridge-erc20',
	'/ima/1.0.x/managing-erc721': '/skale-bridge/ethereum/bridge-erc721',
	'/ima/1.0.x/message-proxy': '/skale-bridge/messaging-layer/message-proxy',
	'/ima/1.0.x/transferring-eth': '/skale-bridge/ethereum/bridge-eth',

	// IMA 1.1.x → SKALE Bridge
	'/ima/1.1.x': '/skale-bridge/overview',
	'/ima/1.1.x/access-control': '/skale-bridge/messaging-layer/connect-custom-contracts',
	'/ima/1.1.x/flows': '/skale-bridge/overview',
	'/ima/1.1.x/getting-started': '/skale-bridge/overview',
	'/ima/1.1.x/managing-erc20': '/skale-bridge/ethereum/bridge-erc20',
	'/ima/1.1.x/whats-new': '/skale-bridge/overview',

	// IMA 1.2.x → SKALE Bridge
	'/ima/1.2.x': '/skale-bridge/overview',
	'/ima/1.2.x/api/mainnet/depositbox': '/skale-bridge/ethereum/bridge-erc20',
	'/ima/1.2.x/api/mainnet/depositboxes/depositboxerc20': '/skale-bridge/ethereum/bridge-erc20',
	'/ima/1.2.x/api/mainnet/linker': '/skale-bridge/overview',
	'/ima/1.2.x/api/mainnet/messageproxyformainnet': '/skale-bridge/messaging-layer/message-proxy',
	'/ima/1.2.x/api/mainnet/skalemanagerclient': '/skale-bridge/overview',
	'/ima/1.2.x/api/schain/tokenmanagers/tokenmanagererc1155': '/skale-bridge/ethereum/bridge-erc1155',
	'/ima/1.2.x/funding-exits': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.2.x/managing-erc1155': '/skale-bridge/ethereum/bridge-erc1155',
	'/ima/1.2.x/managing-erc721': '/skale-bridge/ethereum/bridge-erc721',
	'/ima/1.2.x/message-proxy': '/skale-bridge/messaging-layer/message-proxy',
	'/ima/1.2.x/s2s-transferring-erc1155': '/skale-bridge/skale/bridge-erc1155',
	'/ima/1.2.x/s2s-transferring-erc20': '/skale-bridge/skale/bridge-erc20',
	'/ima/1.2.x/transferring-eth': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.2.x/troubleshooting': '/skale-bridge/overview',
	'/ima/1.2.x/whats-new': '/skale-bridge/overview',

	// IMA 1.3.x → SKALE Bridge
	'/ima/1.3.x': '/skale-bridge/overview',
	'/ima/1.3.x/access-control': '/skale-bridge/messaging-layer/connect-custom-contracts',
	'/ima/1.3.x/flows': '/skale-bridge/overview',
	'/ima/1.3.x/funding-exits': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.3.x/getting-started': '/skale-bridge/overview',
	'/ima/1.3.x/managing-erc1155': '/skale-bridge/ethereum/bridge-erc1155',
	'/ima/1.3.x/managing-erc20': '/skale-bridge/ethereum/bridge-erc20',
	'/ima/1.3.x/managing-erc721': '/skale-bridge/ethereum/bridge-erc721',
	'/ima/1.3.x/message-proxy': '/skale-bridge/messaging-layer/message-proxy',
	'/ima/1.3.x/s2s-transferring-erc1155': '/skale-bridge/skale/bridge-erc1155',
	'/ima/1.3.x/s2s-transferring-erc20': '/skale-bridge/skale/bridge-erc20',
	'/ima/1.3.x/s2s-transferring-erc721': '/skale-bridge/skale/bridge-erc721',
	'/ima/1.3.x/transferring-eth': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.3.x/troubleshooting': '/skale-bridge/overview',
	'/ima/1.3.x/whats-new': '/skale-bridge/overview',

	// IMA 1.3.x-beta → SKALE Bridge
	'/ima/1.3.x-beta': '/skale-bridge/overview',
	'/ima/1.3.x-beta/access-control': '/skale-bridge/messaging-layer/connect-custom-contracts',
	'/ima/1.3.x-beta/api/schain/tokenmanagers/tokenmanagererc20': '/skale-bridge/ethereum/bridge-erc20',
	'/ima/1.3.x-beta/flows': '/skale-bridge/overview',
	'/ima/1.3.x-beta/funding-exits': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.3.x-beta/getting-started': '/skale-bridge/overview',
	'/ima/1.3.x-beta/managing-erc1155': '/skale-bridge/ethereum/bridge-erc1155',
	'/ima/1.3.x-beta/managing-erc20': '/skale-bridge/ethereum/bridge-erc20',
	'/ima/1.3.x-beta/managing-erc721': '/skale-bridge/ethereum/bridge-erc721',
	'/ima/1.3.x-beta/message-proxy': '/skale-bridge/messaging-layer/message-proxy',
	'/ima/1.3.x-beta/s2s-transferring-erc20': '/skale-bridge/skale/bridge-erc20',
	'/ima/1.3.x-beta/s2s-transferring-erc721': '/skale-bridge/skale/bridge-erc721',
	'/ima/1.3.x-beta/security-methods': '/skale-bridge/overview',
	'/ima/1.3.x-beta/transferring-eth': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.3.x-beta/troubleshooting': '/skale-bridge/overview',
	'/ima/1.3.x-beta/whats-new': '/skale-bridge/overview',

	// IMA 1.4.x → SKALE Bridge
	'/ima/1.4.x': '/skale-bridge/overview',
	'/ima/1.4.x/access-control': '/skale-bridge/messaging-layer/connect-custom-contracts',
	'/ima/1.4.x/flows': '/skale-bridge/overview',
	'/ima/1.4.x/funding-exits': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.4.x/getting-started': '/skale-bridge/overview',
	'/ima/1.4.x/managing-erc1155': '/skale-bridge/ethereum/bridge-erc1155',
	'/ima/1.4.x/managing-erc20': '/skale-bridge/ethereum/bridge-erc20',
	'/ima/1.4.x/managing-erc721': '/skale-bridge/ethereum/bridge-erc721',
	'/ima/1.4.x/message-proxy': '/skale-bridge/messaging-layer/message-proxy',
	'/ima/1.4.x/s2s-transferring-erc1155': '/skale-bridge/skale/bridge-erc1155',
	'/ima/1.4.x/s2s-transferring-erc20': '/skale-bridge/skale/bridge-erc20',
	'/ima/1.4.x/s2s-transferring-erc721': '/skale-bridge/skale/bridge-erc721',
	'/ima/1.4.x/security-methods': '/skale-bridge/overview',
	'/ima/1.4.x/transferring-eth': '/skale-bridge/ethereum/bridge-eth',
	'/ima/1.4.x/troubleshooting': '/skale-bridge/overview',
	'/ima/1.4.x/whats-new': '/skale-bridge/overview',

	// ==========================================
	// TOOLS  GENERAL REDIRECTS
	// ==========================================

	// General section redirects
	'/recipes': '/welcome/get-started',
	'/tools': '/welcome/get-started',
	'/technology': '/welcome/get-started',
}